# Generated by Django 3.0.7 on 2021-02-10 15:45

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0008_auto_20201015_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, help_text='Description of the batch', max_length=1023)),
                ('users', models.ManyToManyField(blank=True, help_text='Persons associated to the batch.', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='batchs',
            field=models.ManyToManyField(blank=True, help_text='Batch associated to this session', to='subjects.Batch', verbose_name='Subject Batchs'),
        ),
    ]
