# Generated by Django 3.0.7 on 2021-02-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20210210_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='batchs',
            new_name='batch',
        ),
    ]
