# Generated by Django 3.0.7 on 2021-04-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_remove_session_batch'),
        ('subjects', '0010_auto_20210210_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='batch',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
