# Generated by Django 3.0.7 on 2021-07-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_auto_20210715_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subprojects',
            field=models.ManyToManyField(blank=True, help_text='Subproject associated to this session', to='subjects.Subproject', verbose_name='Subject Subprojects'),
        ),
    ]
