# Generated by Django 3.0.7 on 2021-07-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_auto_20210715_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='implant_weight',
            field=models.FloatField(blank=True, help_text='Implant weight in grams', null=True),
        ),
    ]
