# Generated by Django 3.0.7 on 2021-02-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20210210_1545'),
        ('actions', '0012_change_qc_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Batch', verbose_name='Session Batchj'),
        ),
    ]
