# Generated by Django 3.0.7 on 2021-02-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20210210_1601'),
        ('actions', '0013_session_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Batch', verbose_name='Session Batch'),
        ),
    ]
