# Generated by Django 3.0.7 on 2021-04-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_auto_20210210_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='batch',
        ),
    ]
