# Generated by Django 3.0.7 on 2021-04-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_remove_session_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='dset_types',
            field=models.CharField(blank=True, default='', max_length=1023),
        ),
    ]
