# Generated by Django 3.0.7 on 2021-10-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0016_auto_20211007_1200'),
        ('actions', '0018_session_subproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='winstor_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Winstor_session', verbose_name='Winstor Session'),
        ),
    ]
